### ISSUE TITLE
Ошибка NoneType

### ISSUE THREAD

**Issue by TSecret-GitHub** [TSecret-GitHub/Transacrions-By-TS#2]
Полный текст ошибки:
```bash
Traceback (most recent call last):
  File "TransactionBot By TS.py", line 119, in <module>
    bot.polling(none_stop=True)
  File "/home/ts/.local/lib/python3.8/site-packages/telebot/__init__.py", line 455, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "/home/ts/.local/lib/python3.8/site-packages/telebot/__init__.py", line 513, in __threaded_polling
    raise e
  File "/home/ts/.local/lib/python3.8/site-packages/telebot/__init__.py", line 479, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/home/ts/.local/lib/python3.8/site-packages/telebot/util.py", line 118, in raise_exceptions
    raise self.exception_info
  File "/home/ts/.local/lib/python3.8/site-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "TransactionBot By TS.py", line 104, in callback_inline
    PostgreSQL.create_order_BD(int(environ.get('addr')), int(environ.get('id')), int(environ.get('amount')))
  File "/home/ts/Dev/Transacrions-By-TS/PostgreSQL.py", line 73, in create_order_BD
    cursor.execute("UPDATE transactions_by_ts.users SET balance = '{balance}' WHERE id = '{id}'".format(balance=record_to[0] + amount, id=to_order))
TypeError: 'NoneType' object is not subscriptable
```

Как повторить:
* Запустить бота
* Нажать/Ввести "Перевести"
* Ввести ID
* Ввести кол-во
* Нажать да на Inline-клавиатуре
* Наслаждаться ошибкой :D

**Comment by TSecret-GitHub** [comment]
Исправлено: Commit [e8cd469](https://github.com/TSecret-GitHub/Transacrions-By-TS/commit/e8cd4697984f98fb5567119edfe9d6a4dde3d544) уже залетел в ветку not-tested
